### ISSUE TITLE
Retrieval precision

### ISSUE THREAD

**Issue by bellyqpp** [TonicAI/tonic_validate#145]
I want to know the Retrieval precision.
I try many times. the result always show answer_similarity,augmentation_precision,answer_consistency.No other indicators available
RunData(scores={'answer_similarity': None, 'augmentation_precision': 1.0, 'answer_consistency': 0.0}
![image](https://github.com/TonicAI/tonic_validate/assets/145628806/9f558f57-7f95-4d92-a6dd-2f38d2b04595)
so i want to know if I should pass in any new indicator data or data.can you give me an example? thank you very much.

**Comment by akamor** [comment]
Hello.  Please review [this section of our documentation.](https://github.com/TonicAI/tonic_validate?tab=readme-ov-file#setting-up-the-tonic-validate-scorer).  It shows you how to modify which metrics are run.  In short, the ```ValidateScorer``` takes in an optional list of metrics to use for evaluation.

**Comment by ethan-tonic** [comment]
You can do something like the following to use retrieval precision @bellyqpp 

```python
from tonic_validate import ValidateScorer
from tonic_validate.metrics import AnswerSimilarityMetric, AugmentationPrecisionMetric, AnswerConsistencyMetric, RetrievalPrecisionMetric

scorer = ValidateScorer([
    AnswerSimilarityMetric(),
    AugmentationPrecisionMetric(),
    AnswerConsistencyMetric(),
    RetrievalPrecisionMetric(),
    # Any other metrics you want here
])
```
By the way, in your screenshot, it says the answer similarity metric is `None`. That's usually because you didn't pass a reference answer in. It can also be `None` if there was some scoring failure. To see what information each metric needs for scoring, you can look at [this table](https://github.com/TonicAI/tonic_validate?tab=readme-ov-file#tonic-validate-metrics).
